/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_SCRIPT_LOOKUP_H
#define _SB_INTERNAL_SCRIPT_LOOKUP_H

#include <drx_graphics/unicode/sheenbidi/Headers/SBConfig.h>
#include <drx_graphics/unicode/sheenbidi/Headers/SBScript.h>

#include "SBBase.h"

SB_INTERNAL SBScript LookupScript(SBCodepoint codepoint);

#endif
